### PR TITLE
Merge terrain modification code into master

### PR DESCRIPTION
**Pull request by Binamrad**
This is basically ready for the demo, I think.

### CODE REVIEW

**Comment by Zinzano** [comment]
I'm on my phone atm but I'm guessing that it is the "new terrain" that's conflicting. I will try to rename my terrain file asap and then this merge should be fine.

**Comment by Zinzano** [comment]
WTF! No it says no conflicts!

**Comment by Binamrad** [comment]
Yeah, I renamed it on my end.

**Comment by Zinzano** [comment]
Aha, that explains it. Since there are no conflict I'm totally fine with this merge.

**Pull request merged**
